[build]
  command = "echo 'Building site...'"
  publish = "templates"
  functions = "."

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200